stages:
- name: uploadArchives
  steps:
  - runScriptConfig:
      image: harbor.cedarhd.com/xiancloud/gradle-java-8
      shellScript: |-
        java -version
        gradle clean uploadArchives
timeout: 6000
