stages:
- name: uploadArchives
  steps:
  - runScriptConfig:
      image: amd64/gradle:4.10-jre8-slim
      shellScript: |-
        java -version
        #gradle clean uploadArchives closeAndReleaseRepository
timeout: 60
